version: '3.9'
services:
  postgres_db:
    image: 'postgres:latest'
    container_name: postgres_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  my-bento:
    container_name: my-bento
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      NODE_ENV: ${NODE_ENV}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_KEY: ${JWT_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    depends_on:
      - postgres_db
    volumes:
      # - ./server:/var/www
      - ./server/src:/app/src

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   restart: unless-stopped
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # node-exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   container_name: node-exporter
  #   command:
  #     - '--path.rootfs=/host'
  #   network_mode: host
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - 'host_metrics:/host:ro,rslave'

  # postgres-exporter:
  #   image: prometheuscommunity/postgres-exporter
  #   container_name: postgres-exporter
  #   restart: unless-stopped
  #   ports:
  #     - 9187:9187
  #   environment:
  #     DATA_SOURCE_NAME: ${DB_URL}
  #   links:
  #     - postgres
  #     - prometheus

volumes:
  db_data:
  # host_metrics: