server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - loki
        labels:
          job: varlogs
          __path__: /var/log/*my-bento-log.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            traceId: traceId
            msg: message
      - labels:
          level:
          traceId:
          msg:
      - timestamp:
          source: time
          format: RFC3339
